use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 2
  autocomplete: 'duckduckgo'

server:
  secret_key: "QwErTyUiOpAsDfGhJkLzXcVbNm" 
  limiter: true
  image_proxy: true
  base_url: http:/searxng.koyeb.app 

redis:
  url: unix:///usr/local/searxng-redis/run/redis.sock?db=0

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'

engines:
  - name: google
  - name: duckduckgo
  - name: bing

